version: 2
jobs:
  # local test:
  #   docker:
  #     - image: circleci/php:7.3-node-browsers
  #   steps:
  #     - checkout
  #     - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
  #     - run: sudo docker-php-ext-install zip
  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #           # "composer.lock" can be used if it is committed to the repo
  #           - v1-dependencies-{{ checksum "composer.json" }}
  #           # fallback to using the latest cache if no exact match is found
  #           - v1-dependencies-
  #     - run: composer install -n --prefer-dist
  #     - run: ./vendor/bin/phpunit
  #     #- sonarcloud/scan_with_npm:
  #      # context: sonarcloud
  #     #- sonarcloud/scan:
  #      # context: sonarcloud
  test builder:
    docker:
      - image: cimg/go:1.16

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies
      - run: npm install
      - run: cd wdio && npm install @wdio/cli
      # - run: apt-get install sudo # https://discuss.circleci.com/t/sudo-command-not-found/14208/4
      # - run: sudo apt update
      - run: chmod -R 777 wdio
      - run: apt-get install libnss
      - run: apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev
      - run: 
          command: npx wdio run wdio.conf.js 
          name: running test
      # - run:
      #     name: Download Selenium Standalone Server
      #     command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run:
      #     name: Start Selenium Standalone Server
      #     command: java -jar selenium-server-standalone-3.5.3.jar -log report/selenium.log
      #     background: true
      # - run:
      #     name: Install Node Modules
      #     command: npm install
      # - run:
      #     name: Test
      #     command: npx wdio run wdio.conf.js
      # - store_test_results:
      #     path: report
      

  # test chrome:
  #   docker:
  #     - image: circleci/node:jessie-browsers
  #   steps:
  #     - checkout
  #     - run: cd wdio && npm install -g npm@7.15.0
  #     - run: cd wdio && npm install @wdio/cli
  #     - run:
  #         name: Make Report Directory
  #         command: mkdir report
  #     - run:
  #         name: Download Selenium Standalone Server
  #         command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
  #     - run:
  #         name: Start Selenium Standalone Server
  #         command: java -jar selenium-server-standalone-3.5.3.jar -log report/selenium.log
  #         background: true
  #     - run:
  #         name: Install Node Modules
  #         command: npm install
  #     - run:
  #         name: Test
  #         command: npx wdio run wdio.conf.js
  #     - store_test_results:
  #         path: report

workflows:
  version: 2
  # main:
  #   jobs:
  #     - local test
  test:
    jobs:
      - test builder
      
  

      
  
      

